
# tasks file for roles/db

- name: Remove old database container
  docker_container:
    name: database
    state: absent

- name: Launch database container
  docker_container:
    name: database
    image: wendy2001/tp-devops-database
    pull: true
    state: started
    restart_policy: unless-stopped
    env:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    networks:
      - name: app-network
